export const constants = {
  mail_error: 'Error in Sending Mail',
  no_content: 'No Content',
  created: 'Created',
  confirmation: 'confirmation',
  leader_info: 'lead_info',
  BRANDING: 'BRANDING',
  DATA_SECURITY: 'DATA_SECURITY',
  LEAD_INFO: 'LEAD_INFO',
  ES_CLOUD_SERVICE: 'ES_CLOUD_SERVICE',
  ES_CABLE_SERVICE: 'ES_CABLE_SERVICE',
  ES_CARRIER_SERVICE: 'ES_CARRIER_SERVICE',
  ES_SDWAN_SERVICE: 'ES_SDWAN_SERVICE',
  CONSULTATION_SERVICE: 'CONSULTATION_SERVICE',
};
